// Dev/test only: read a run log from disk so /case/fixture-<name> can replay it (P3).
// Recorded real runs live in fixtures/runs/<name>.jsonl. Names starting with `synthetic-` are the
// unit-test logs in lib/runs/__tests__/logs (generated by the real pipeline with a fake model);
// they are served only so the case page can be built and tested before a real recording exists.
// Server code only (node:fs). Never imported by a client component.

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { isRunEvent, type RunEvent } from './types';

const NAME = /^[a-z0-9][a-z0-9-]{0,63}$/;

/**
 * On in dev and test. A local production build can opt in with ACHP_FIXTURES=1 (server-side, never NEXT_PUBLIC) to
 * measure performance on a real bundle (P8, P10); a deployment never sets it.
 */
export function fixtureEnabled(): boolean {
  return process.env.NODE_ENV !== 'production' || process.env.ACHP_FIXTURES === '1';
}

function fixturePath(name: string): string | null {
  if (!NAME.test(name)) return null;
  const root = process.cwd();
  const file = name.startsWith('synthetic-')
    ? path.join(root, 'lib', 'runs', '__tests__', 'logs', `${name}.jsonl`)
    : path.join(root, 'fixtures', 'runs', `${name}.jsonl`);
  return existsSync(file) ? file : null;
}

/** The fixture's events in seq order, or null if there is no such fixture (or fixtures are off). */
export function readFixture(name: string): RunEvent[] | null {
  if (!fixtureEnabled()) return null;
  const file = fixturePath(name);
  if (!file) return null;
  const events = readFileSync(file, 'utf8')
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as unknown)
    .filter(isRunEvent);
  return events.length ? events.sort((a, b) => a.seq - b.seq) : null;
}

export interface ReplayOptions {
  /** Playback rate: 4 plays the recorded timing four times faster. */
  speed: number;
  /** Test hook: the first connection closes after this seq without a terminal event. */
  drop: number | null;
}

/** Options travel in one path segment, e.g. `speed=4,drop=12` (the connection appends /runs/…). */
export function parseReplayOptions(segment: string | undefined): ReplayOptions {
  const out: ReplayOptions = { speed: 1, drop: null };
  for (const part of (segment ?? '').split(',')) {
    const [k, v] = part.split('=');
    const n = Number(v);
    if (k === 'speed' && Number.isFinite(n)) out.speed = Math.min(50, Math.max(0.25, n));
    if (k === 'drop' && Number.isInteger(n) && n > 0) out.drop = n;
  }
  return out;
}

export function replayOptionsSegment(o: Partial<ReplayOptions>): string {
  const parts = [`speed=${o.speed ?? 1}`];
  if (o.drop) parts.push(`drop=${o.drop}`);
  return parts.join(',');
}

// ── Samples: recorded real checks that ship with the app ──────────────────────────────────────────────────────────
// Unlike fixtures (dev and test replays), a sample is served in production: it is a stored case, opened at
// /case/sample-<name> and labelled as a recorded example. Only recorded runs qualify, never synthetic test logs.

export const SAMPLE_PREFIX = 'sample-';

export const SAMPLES = [
  { name: 'exercise-mixed', id: 'sample-exercise-mixed' },
  { name: 'contradicted-strong', id: 'sample-contradicted-strong' },
  { name: 'all-supported', id: 'sample-all-supported' },
] as const;

export function isSampleId(id: string): boolean {
  return SAMPLES.some((s) => s.id === id);
}

/** A sample's recorded events in seq order, or null when `id` is not a sample. Works in production. */
export function readSample(id: string): RunEvent[] | null {
  const sample = SAMPLES.find((s) => s.id === id);
  if (!sample) return null;
  const file = path.join(process.cwd(), 'fixtures', 'runs', `${sample.name}.jsonl`);
  if (!existsSync(file)) return null;
  const events = readFileSync(file, 'utf8')
    .split(/\r?\n/)
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as unknown)
    .filter(isRunEvent);
  return events.length ? events.sort((a, b) => a.seq - b.seq) : null;
}
