import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type { Page } from '@playwright/test';
import { initialRunState, lanes, reduceRun } from '../lib/runs/reducer';
import type { RunEvent } from '../lib/runs/types';

// Which log a case e2e test replays. The recorded fixture from fixtures-plan.md is preferred; until
// it's recorded against a backend with a model key, the unit-test log of the same shape stands in
// (generated by the real pipeline + bus with a fake model; lib/runs/__tests__/logs).

const WEB = path.resolve(__dirname, '..');

export function pickFixture(recorded: string, synthetic: string): { name: string; events: RunEvent[] } {
  const rec = path.join(WEB, 'fixtures', 'runs', `${recorded}.jsonl`);
  const name = existsSync(rec) ? recorded : synthetic;
  const file = existsSync(rec) ? rec : path.join(WEB, 'lib', 'runs', '__tests__', 'logs', `${synthetic}.jsonl`);
  const events = readFileSync(file, 'utf8')
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as RunEvent);
  return { name, events };
}

/** Every lane state change the log implies, in event order ("agent:state"). */
export function expectedTransitions(events: RunEvent[]): string[] {
  let s = initialRunState();
  const out: string[] = [];
  for (const e of events) {
    const before = Object.fromEntries(lanes(s).map((l) => [l.id, l.state]));
    s = reduceRun(s, e);
    for (const l of lanes(s)) if (before[l.id] !== l.state) out.push(`${l.id}:${l.state}`);
  }
  return out;
}

export function finalLaneStates(events: RunEvent[]): Record<string, string> {
  const s = events.reduce(reduceRun, initialRunState());
  return Object.fromEntries(lanes(s).map((l) => [l.id, l.state]));
}

export interface SeenTransition {
  t: string;
  /** Which DOM commit showed it (one MutationObserver callback = one React commit). */
  commit: number;
}

/**
 * The page never shows a lane change before an earlier one in the log. A render may apply several
 * events at once (then the DOM writes them in tree order, so order *within* a commit means
 * nothing); across commits, event order must hold, and each lane's own states must follow the log.
 * Returns a list of problems (empty = fine).
 */
export function orderProblems(seen: SeenTransition[], expected: string[]): string[] {
  const problems: string[] = [];
  const at: { t: string; commit: number; index: number }[] = [];
  const next = new Map<string, number>(); // per agent: where to look next in `expected`
  for (const s of seen) {
    const agent = s.t.split(':')[0];
    let i = next.get(agent) ?? 0;
    while (i < expected.length && expected[i] !== s.t) i += 1;
    if (i === expected.length) {
      problems.push(`${s.t} is out of order for its lane or never happens in the log`);
      continue;
    }
    next.set(agent, i + 1);
    at.push({ ...s, index: i });
  }
  at.sort((a, b) => a.index - b.index);
  for (let k = 1; k < at.length; k += 1) {
    if (at[k].commit < at[k - 1].commit) {
      problems.push(`${at[k].t} (commit ${at[k].commit}) showed before ${at[k - 1].t} (commit ${at[k - 1].commit})`);
    }
  }
  return problems;
}

export async function healthOk(page: Page) {
  await page.route('**/health', (route) => route.fulfill({ json: { status: 'ok', pipeline_mode: 'online', kb_count: 0 } }));
}

/** Record every lane state the page shows, as it changes (installed before the page loads). */
export async function watchLanes(page: Page) {
  await page.addInitScript(() => {
    const w = window as unknown as { __lanes: { t: string; commit: number }[] };
    w.__lanes = [];
    let commit = 0;
    const note = (el: Element) => {
      const agent = el.getAttribute('data-agent');
      const state = el.getAttribute('data-state');
      if (!agent || !state || el.closest('[role="dialog"]')) return;
      const entry = `${agent}:${state}`;
      const last = [...w.__lanes].reverse().find((x) => x.t.startsWith(`${agent}:`));
      if (last?.t !== entry) w.__lanes.push({ t: entry, commit });
    };
    new MutationObserver((records) => {
      commit += 1;
      for (const r of records) {
        if (r.type === 'attributes' && r.target instanceof Element) note(r.target);
        for (const n of r.addedNodes) {
          if (n instanceof Element) {
            if (n.matches('li[data-agent]')) note(n);
            n.querySelectorAll('li[data-agent]').forEach(note);
          }
        }
      }
    }).observe(document, { subtree: true, childList: true, attributes: true, attributeFilter: ['data-state'] });
  });
}
