"""
ACHP Assay: reference implementation of the metric instruments (kit 11_THE_ASSAY.md).

Zero dependencies (stdlib only). This file is the source of truth; `assay.ts` is a line-for-line port and
`vectors.json` (generated by `python assay.py --vectors`) pins the two together.

Metric full forms (ACHP paper, Sec. IV):
  CTS  Consensus Truth Score           (higher = better supported)
  PCS  Perspective Completeness Score  (higher = more viewpoints present)
  BIS  Bias Impact Score               (higher = MORE bias; enters the composite as 1 - BIS)
  NSS  Narrative Stance Score          (higher = more neutral stance)
  EPS  Epistemic Position Score        (higher = better-calibrated certainty language)
  C    Composite = (CTS + PCS + (1 - BIS) + NSS + EPS) / 5

Two formula modes:
  "paper"  equations (1)-(6) exactly as published: narrative alignment and Judge NSS are independent inputs.
  "code"   what apps/api/achp/core/core_pipeline.py computes today: narrative alignment := 1 - framing,
           and Judge NSS falls back to NSS_proxy(BIS, framing) when the Judge omits it.

Instruments (all deterministic, all pure functions of the raw signals):
  compute()          metrics + composite + formula verdict (with clamp flags)
  ledger()           exact Shapley attribution of C against a declared reference sheet (double-entry: balances)
  tipping_point()    smallest single-signal change that flips the formula verdict (verdict robustness)
  two_key()          agreement between the Judge's verdict and the formula verdict
  masking()          narrative lift, Quiet Falsehood Index (QFI) and the masking flag
  leverage()         local sensitivity dC/dsignal and each signal's share of total leverage
  lineage()          which raw signals feed which metrics (fan-out, reuse)
  integrity_map_xy() coordinates + quadrant for the /runs Integrity Map
"""
from __future__ import annotations

import itertools
import json
import math
import sys
from dataclasses import dataclass, field, asdict, replace
from typing import Dict, List, Optional, Tuple

FORMULA_VERSION = "achp-metrics/1.0"  # equations (1)-(6) of the ACHP paper; bump if weights change

METRICS = ("CTS", "PCS", "BIS", "NSS", "EPS")
FULL_FORMS = {
    "CTS": "Consensus Truth Score",
    "PCS": "Perspective Completeness Score",
    "BIS": "Bias Impact Score",
    "NSS": "Narrative Stance Score",
    "EPS": "Epistemic Position Score",
}
# Human agreement from the paper's calibration study (Fig. 13, Pearson r, n = 200 claims).
HUMAN_AGREEMENT_R = {"CTS": 0.81, "PCS": 0.74, "BIS": 0.69, "NSS": 0.72, "EPS": 0.78}

# Verdict scale, exactly as verdict_from_composite() in core_pipeline.py (half-open, lower bound inclusive).
SCALE: Tuple[Tuple[float, str], ...] = (
    (0.85, "TRUE"),
    (0.70, "MOSTLY_TRUE"),
    (0.50, "MIXED"),
    (0.30, "MOSTLY_FALSE"),
    (0.00, "FALSE"),
)
VERDICT_ORDER = ["FALSE", "MOSTLY_FALSE", "MIXED", "MOSTLY_TRUE", "TRUE"]
FRAME_BOOST = {"delegitimize": 0.15, "conspiracy": 0.15, "alarm": 0.05}
FRAMES = ("neutral", "alarm", "delegitimize")  # representative values for the three boost levels

# Raw signals. Names follow the paper's notation.
SIGNAL_INFO = {
    "fA":    ("Adversary A factual score", "continuous"),
    "jCTS":  ("Judge raw CTS", "continuous"),
    "s_nil": ("NIL bias score (BiasGroq)", "continuous"),
    "s_fr":  ("Framing score (FramingCosine)", "continuous"),
    "pol":   ("|VADER polarity|", "continuous"),
    "frame": ("Dominant frame", "categorical"),
    "fB":    ("Adversary B perspective score", "continuous"),
    "s_pcs": ("NIL perspective score", "continuous"),
    "n_miss": ("Missing perspectives (count)", "count"),
    "a_narr": ("Narrative alignment", "continuous"),
    "jNSS":  ("Judge raw NSS", "continuous"),
    "v_eps": ("VADER epistemic score", "continuous"),
    "hr":    ("Hedge ratio", "continuous"),
}
FACTUAL_SIGNALS = ("fA", "jCTS")


@dataclass(frozen=True)
class Signals:
    fA: float
    jCTS: float
    s_nil: float
    s_fr: float
    pol: float
    frame: str
    fB: float
    s_pcs: float
    n_miss: int
    v_eps: float
    hr: float
    a_narr: Optional[float] = None  # paper mode input; ignored in code mode (derived as 1 - s_fr)
    jNSS: Optional[float] = None    # paper mode input; in code mode None -> NSS_proxy(BIS, s_fr)


# The reference sheet: a claim with every signal at its neutral midpoint. Ledger balances are relative to it.
REFERENCE = Signals(fA=0.5, jCTS=0.5, s_nil=0.5, s_fr=0.5, pol=0.5, frame="neutral",
                    fB=0.5, s_pcs=0.5, n_miss=5, v_eps=0.5, hr=1 / 6, a_narr=0.5, jNSS=0.5)


def _clamp(x: float) -> Tuple[float, bool]:
    y = min(1.0, max(0.0, x))
    return y, (y != x)


def _r4(x: float) -> float:
    return round(x + 0.0, 4)


def features(mode: str, s: Signals) -> List[str]:
    """Signals that are free inputs in this mode (derived ones are excluded from attribution)."""
    names = ["fA", "jCTS", "s_nil", "s_fr", "pol", "frame", "fB", "s_pcs", "n_miss", "v_eps", "hr"]
    if mode == "paper":
        names += ["a_narr", "jNSS"]
    elif s.jNSS is not None:
        names += ["jNSS"]
    return names


def compute(s: Signals, mode: str = "code") -> Dict:
    if mode not in ("paper", "code"):
        raise ValueError("mode must be 'paper' or 'code'")
    clamped: List[str] = []

    boost = FRAME_BOOST.get(s.frame, 0.0)
    bis, c = _clamp(0.55 * s.s_nil + 0.25 * s.s_fr + 0.12 * s.pol + boost); bis = _r4(bis)
    if c: clamped.append("BIS")
    eps, c = _clamp(0.70 * s.v_eps + 0.20 * (1 - s.s_fr) + 0.10 * min(1.0, s.hr * 3)); eps = _r4(eps)
    if c: clamped.append("EPS")
    cts, c = _clamp(0.40 * s.fA + 0.35 * s.jCTS + 0.15 * (1 - bis) + 0.10 * eps); cts = _r4(cts)
    if c: clamped.append("CTS")
    pcs, c = _clamp(0.50 * s.fB + 0.30 * s.s_pcs + 0.20 * (1 - min(1.0, s.n_miss / 10))); pcs = _r4(pcs)
    if c: clamped.append("PCS")

    if mode == "paper":
        a_narr = 0.5 if s.a_narr is None else s.a_narr
        j_nss = 0.5 if s.jNSS is None else s.jNSS
    else:
        a_narr = 1.0 - s.s_fr                                   # core_pipeline.py: "simpler alignment proxy"
        j_nss = s.jNSS if s.jNSS is not None else _r4(max(0.0, 1.0 - 0.6 * bis - 0.4 * s.s_fr))  # NSS_proxy
    nss, c = _clamp(0.40 * (1 - s.s_fr) + 0.35 * a_narr + 0.25 * j_nss); nss = _r4(nss)
    if c: clamped.append("NSS")

    composite = _r4((cts + pcs + (1 - bis) + nss + eps) / 5)
    return {
        "mode": mode,
        "formula_version": FORMULA_VERSION,
        "metrics": {"CTS": cts, "PCS": pcs, "BIS": bis, "NSS": nss, "EPS": eps},
        "composite": composite,
        "formula_verdict": verdict_of(composite),
        "clamped": clamped,
    }


def verdict_of(c: float) -> str:
    for threshold, label in SCALE:
        if c >= threshold:
            return label
    return "FALSE"


def _C(s: Signals, mode: str) -> float:
    return compute(s, mode)["composite"]


def _unrounded_C(s: Signals, mode: str) -> float:
    """Composite without 4-dp rounding, used only where tiny rounding steps would pollute a derivative."""
    boost = FRAME_BOOST.get(s.frame, 0.0)
    bis = min(1.0, max(0.0, 0.55 * s.s_nil + 0.25 * s.s_fr + 0.12 * s.pol + boost))
    eps = min(1.0, max(0.0, 0.70 * s.v_eps + 0.20 * (1 - s.s_fr) + 0.10 * min(1.0, s.hr * 3)))
    cts = min(1.0, max(0.0, 0.40 * s.fA + 0.35 * s.jCTS + 0.15 * (1 - bis) + 0.10 * eps))
    pcs = min(1.0, max(0.0, 0.50 * s.fB + 0.30 * s.s_pcs + 0.20 * (1 - min(1.0, s.n_miss / 10))))
    if mode == "paper":
        a_narr = 0.5 if s.a_narr is None else s.a_narr
        j_nss = 0.5 if s.jNSS is None else s.jNSS
    else:
        a_narr = 1.0 - s.s_fr
        j_nss = s.jNSS if s.jNSS is not None else max(0.0, 1.0 - 0.6 * bis - 0.4 * s.s_fr)
    nss = min(1.0, max(0.0, 0.40 * (1 - s.s_fr) + 0.35 * a_narr + 0.25 * j_nss))
    return (cts + pcs + (1 - bis) + nss + eps) / 5


# ─────────────────────────────── Integrity Ledger (exact Shapley) ───────────────────────────────

def ledger(s: Signals, mode: str = "code", reference: Signals = REFERENCE) -> Dict:
    """Exact Shapley attribution of C(s) - C(reference) across the free signals of this mode.

    Double-entry property: opening + sum(entries) == closing (up to float error) for ANY formula,
    including clamps, because Shapley values are efficient. Uses unrounded C so rounding can't leak in.
    """
    names = features(mode, s)
    n = len(names)
    ref = reference
    if mode == "code" and s.jNSS is None:
        ref = replace(ref, jNSS=None)

    def value(mask: int) -> float:
        kw = {}
        for i, name in enumerate(names):
            kw[name] = getattr(s, name) if mask >> i & 1 else getattr(ref, name)
        return _unrounded_C(replace(ref, **kw), mode)

    v = [value(m) for m in range(1 << n)]
    fact = [math.factorial(k) for k in range(n + 1)]
    phi = [0.0] * n
    for i in range(n):
        bit = 1 << i
        acc = 0.0
        for m in range(1 << n):
            if m & bit:
                continue
            k = bin(m).count("1")
            acc += fact[k] * fact[n - k - 1] / fact[n] * (v[m | bit] - v[m])
        phi[i] = acc
    opening, closing = v[0], v[(1 << n) - 1]
    entries = sorted(
        ({"signal": names[i], "label": SIGNAL_INFO[names[i]][0], "value": getattr(s, names[i]),
          "reference": getattr(ref, names[i]), "amount": phi[i]} for i in range(n)),
        key=lambda e: -abs(e["amount"]))
    return {
        "mode": mode,
        "opening_balance": opening,
        "entries": entries,
        "closing_balance": closing,
        "check": abs(opening + sum(phi) - closing),
        "credits": sum(p for p in phi if p > 0),
        "debits": sum(p for p in phi if p < 0),
        "factual_share": sum(abs(e["amount"]) for e in entries if e["signal"] in FACTUAL_SIGNALS)
                         / max(1e-12, sum(abs(p) for p in phi)),
    }


# ─────────────────────────────── Tipping Point (verdict robustness) ───────────────────────────────

def _domain(name: str) -> List:
    kind = SIGNAL_INFO[name][1]
    if kind == "categorical":
        return list(FRAMES)
    if kind == "count":
        return list(range(0, 11))
    return [i / 1000 for i in range(0, 1001)]


def tipping_point(s: Signals, mode: str = "code") -> Dict:
    """For each free signal, the nearest value (others fixed) at which the formula verdict changes.

    Continuous signals are scanned on a 0.001 grid, then refined by bisection to 1e-6. Distances are in
    signal units (0-1 scale; counts are divided by 10 so they are comparable). Returns the flips sorted
    by distance, the minimum distance and a robustness band.
    """
    base = compute(s, mode)
    v0 = base["formula_verdict"]
    flips = []
    for name in features(mode, s):
        cur = getattr(s, name)
        kind = SIGNAL_INFO[name][1]
        best = None
        if kind == "categorical":
            for val in _domain(name):
                if val == cur:
                    continue
                v1 = verdict_of(_C(replace(s, **{name: val}), mode))
                if v1 != v0:
                    best = (val, 1.0, v1)  # a categorical change counts as distance 1 (a different frame)
                    break
        elif kind == "count":
            for val in sorted(_domain(name), key=lambda x: abs(x - cur)):
                if val == cur:
                    continue
                v1 = verdict_of(_C(replace(s, **{name: val}), mode))
                if v1 != v0:
                    best = (val, abs(val - cur) / 10, v1)
                    break
        else:
            grid = _domain(name)
            for direction in (-1, 1):
                prev = cur
                for g in (x for x in (grid if direction > 0 else reversed(grid))
                          if (x > cur if direction > 0 else x < cur)):
                    v1 = verdict_of(_C(replace(s, **{name: g}), mode))
                    if v1 != v0:
                        lo, hi = prev, g       # verdict equals v0 at lo, differs at hi
                        for _ in range(40):
                            mid = (lo + hi) / 2
                            if verdict_of(_C(replace(s, **{name: mid}), mode)) == v0:
                                lo = mid
                            else:
                                hi = mid
                        d = abs(hi - cur)
                        vnew = verdict_of(_C(replace(s, **{name: hi}), mode))
                        if best is None or d < best[1]:
                            best = (hi, d, vnew)       # unrounded: rounding could step back over the boundary
                        break
                    prev = g
        if best is not None:
            flips.append({"signal": name, "label": SIGNAL_INFO[name][0], "from": cur, "to": best[0],
                          "distance": best[1], "new_verdict": best[2]})
    flips.sort(key=lambda f: f["distance"])
    continuous = [f for f in flips if SIGNAL_INFO[f["signal"]][1] != "categorical"]
    d = continuous[0]["distance"] if continuous else None
    band = "settled" if d is None or d >= 0.25 else ("firm" if d >= 0.10 else "fragile")
    return {"verdict": v0, "composite": base["composite"], "flips": flips, "min_distance": d, "band": band}


# ─────────────────────────────── Two-Key Verdict ───────────────────────────────

def two_key(judge_verdict: str, formula_verdict: str) -> Dict:
    """Compare the Judge agent's verdict (key 1) with the published formula's verdict (key 2)."""
    special = {"UNVERIFIABLE", "BLOCKED"}
    if judge_verdict in special:
        return {"state": "not_applicable", "steps": None, "judge": judge_verdict, "formula": formula_verdict}
    if judge_verdict not in VERDICT_ORDER:
        raise ValueError(f"unknown verdict {judge_verdict}")
    steps = abs(VERDICT_ORDER.index(judge_verdict) - VERDICT_ORDER.index(formula_verdict))
    state = "agree" if steps == 0 else ("adjacent" if steps == 1 else "split")
    return {"state": state, "steps": steps, "judge": judge_verdict, "formula": formula_verdict}


# ─────────────────────────────── Masking: Narrative Lift & Quiet Falsehood Index ───────────────────────────────

QFI_FLAG = 0.45          # experimental threshold, to be calibrated (11_THE_ASSAY.md §6)
WEAK_FACTS_CTS = 0.40


def masking(result: Dict) -> Dict:
    m = result["metrics"]
    calm = ((1 - m["BIS"]) + m["NSS"] + m["EPS"]) / 3          # how measured / neutral the claim reads
    lift = result["composite"] - m["CTS"]                         # = 4/5 * (mean narrative - CTS)
    qfi = (1 - m["CTS"]) * calm                                   # Quiet Falsehood Index in [0, 1]
    weak = m["CTS"] < WEAK_FACTS_CTS
    lifted = VERDICT_ORDER.index(result["formula_verdict"]) >= VERDICT_ORDER.index("MIXED")
    return {
        "calm": round(calm, 4),
        "narrative_lift": round(lift, 4),
        "qfi": round(qfi, 4),
        "masking": bool(weak and lifted),
        "quiet_falsehood": bool(weak and qfi >= QFI_FLAG),
    }


# ─────────────────────────────── Leverage & Lineage ───────────────────────────────

def leverage(s: Signals, mode: str = "code", h: float = 1e-4) -> Dict:
    """Central-difference dC/dx for each continuous free signal at s (counts per +1 item, frame skipped)."""
    out = {}
    for name in features(mode, s):
        kind = SIGNAL_INFO[name][1]
        if kind == "categorical":
            continue
        cur = getattr(s, name)
        if kind == "count":
            lo, hi = max(0, cur - 1), cur + 1
            g = (_unrounded_C(replace(s, **{name: hi}), mode) - _unrounded_C(replace(s, **{name: lo}), mode)) / (hi - lo)
        else:
            lo, hi = max(0.0, cur - h), min(1.0, cur + h)
            g = (_unrounded_C(replace(s, **{name: hi}), mode) - _unrounded_C(replace(s, **{name: lo}), mode)) / (hi - lo)
        out[name] = g
    total = sum(abs(v) for k, v in out.items() if SIGNAL_INFO[k][1] == "continuous")
    shares = {k: abs(v) / total for k, v in out.items() if SIGNAL_INFO[k][1] == "continuous"}
    return {"mode": mode, "gradient": out, "share": shares,
            "factual_share": sum(shares.get(k, 0) for k in FACTUAL_SIGNALS),
            "top": max(shares, key=shares.get)}


LINEAGE = {
    # metric -> signals that feed it directly (paper mode); code mode adds the derived edges below
    "BIS": ["s_nil", "s_fr", "pol", "frame"],
    "EPS": ["v_eps", "s_fr", "hr"],
    "CTS": ["fA", "jCTS", "BIS", "EPS"],
    "PCS": ["fB", "s_pcs", "n_miss"],
    "NSS": ["s_fr", "a_narr", "jNSS"],
}
LINEAGE_CODE_EXTRA = {"NSS": ["s_fr (as 1 - framing alignment)", "BIS (via NSS_proxy)", "s_fr (via NSS_proxy)"]}


def lineage(mode: str = "code", judge_nss_present: bool = True) -> Dict:
    """Fan-out of each raw signal into the five metrics (counting indirect paths through BIS/EPS into CTS).

    In code mode the framing score also enters NSS as the alignment proxy (1 - s_fr), and, when the Judge
    omits nss_raw, a third time through NSS_proxy (-0.4 * s_fr, plus BIS)."""
    reach: Dict[str, set] = {}
    for metric, inputs in LINEAGE.items():
        for i in inputs:
            reach.setdefault(i, set()).add(metric)
    for mid in ("BIS", "EPS"):  # metrics that feed CTS
        for sig, ms in reach.items():
            if mid in ms:
                ms.add("CTS")
    uses = {sig: sorted(ms) for sig, ms in reach.items() if sig not in METRICS}
    paths = {sig: sum(1 for inputs in LINEAGE.values() for i in inputs if i == sig) for sig in uses}
    if mode == "code":
        paths["s_fr"] += 1 if judge_nss_present else 2   # alignment := 1 - s_fr (+ NSS_proxy's -0.4 * s_fr)
        uses.pop("a_narr", None)
        paths.pop("a_narr", None)
    return {"mode": mode, "reaches": uses, "direct_paths": paths,
            "most_reused": max(paths, key=paths.get)}


# ─────────────────────────────── Integrity Map ───────────────────────────────

def integrity_map_xy(result: Dict) -> Dict:
    m = result["metrics"]
    x = m["CTS"]
    y = ((1 - m["BIS"]) + m["NSS"] + m["EPS"]) / 3
    quadrant = ("sound" if y >= 0.5 else "true_but_loaded") if x >= 0.5 else \
               ("quiet_falsehood" if y >= 0.5 else "loud_falsehood")
    return {"x": round(x, 4), "y": round(y, 4), "quadrant": quadrant}


def assay(s: Signals, judge_verdict: str, mode: str = "code") -> Dict:
    """Everything the `assay.computed` event carries (06_AGENT_STATE_SPEC.md §3.1)."""
    r = compute(s, mode)
    return {
        **r,
        "signals": asdict(s),
        "judge_verdict": judge_verdict,
        "two_key": two_key(judge_verdict, r["formula_verdict"]),
        "ledger": ledger(s, mode),
        "tipping_point": tipping_point(s, mode),
        "masking": masking(r),
        "leverage": leverage(s, mode),
        "integrity_map": integrity_map_xy(r),
        "human_agreement_r": HUMAN_AGREEMENT_R,
    }


# ─────────────────────────────── Sample signals (illustrative, used by the prototype) ───────────────────────────────

SAMPLES = {
    "exercise_mixed": (Signals(fA=0.62, jCTS=0.55, s_nil=0.22, s_fr=0.18, pol=0.30, frame="neutral",
                               fB=0.45, s_pcs=0.50, n_miss=3, v_eps=0.40, hr=0.05), "MIXED"),
    "quiet_falsehood": (Signals(fA=0.08, jCTS=0.12, s_nil=0.10, s_fr=0.08, pol=0.05, frame="neutral",
                                fB=0.70, s_pcs=0.65, n_miss=1, v_eps=0.72, hr=0.20), "FALSE"),
    "loud_falsehood": (Signals(fA=0.10, jCTS=0.10, s_nil=0.80, s_fr=0.70, pol=0.85, frame="delegitimize",
                               fB=0.30, s_pcs=0.25, n_miss=6, v_eps=0.20, hr=0.00), "FALSE"),
    "sound_true": (Signals(fA=0.90, jCTS=0.88, s_nil=0.10, s_fr=0.10, pol=0.10, frame="neutral",
                           fB=0.80, s_pcs=0.75, n_miss=1, v_eps=0.70, hr=0.15), "TRUE"),
    "true_but_loaded": (Signals(fA=0.85, jCTS=0.80, s_nil=0.70, s_fr=0.60, pol=0.80, frame="alarm",
                                fB=0.40, s_pcs=0.35, n_miss=5, v_eps=0.25, hr=0.00), "MOSTLY_TRUE"),
    "paper_fig9": (None, "MOSTLY_FALSE"),  # metrics only, from the paper's Fig. 9 / Fig. 11
}
PAPER_FIG9_METRICS = {"CTS": 0.52, "PCS": 0.51, "BIS": 0.42, "NSS": 0.75, "EPS": 0.30}


def from_metrics(metrics: Dict[str, float]) -> Dict:
    """Two-key / masking on published metric values when raw signals are not available (e.g. paper figures)."""
    c = _r4((metrics["CTS"] + metrics["PCS"] + (1 - metrics["BIS"]) + metrics["NSS"] + metrics["EPS"]) / 5)
    return {"metrics": metrics, "composite": c, "formula_verdict": verdict_of(c)}


def _vectors() -> Dict:
    out = {"formula_version": FORMULA_VERSION, "cases": []}
    for key, (sig, judge) in SAMPLES.items():
        if sig is None:
            continue
        for mode in ("code", "paper"):
            s = sig if mode == "code" else replace(sig, a_narr=round(1 - sig.s_fr, 4), jNSS=0.6)
            a = assay(s, judge, mode)
            out["cases"].append({"name": key, "mode": mode, "signals": asdict(s), "judge": judge,
                                 "metrics": a["metrics"], "composite": a["composite"],
                                 "formula_verdict": a["formula_verdict"], "two_key": a["two_key"]["state"],
                                 "ledger": {e["signal"]: round(e["amount"], 9) for e in a["ledger"]["entries"]},
                                 "opening": round(a["ledger"]["opening_balance"], 9),
                                 "tipping_min": a["tipping_point"]["min_distance"],
                                 "tipping_first": a["tipping_point"]["flips"][0]["signal"] if a["tipping_point"]["flips"] else None,
                                 "masking": a["masking"], "map": a["integrity_map"]})
    return out


if __name__ == "__main__":
    if "--vectors" in sys.argv:
        json.dump(_vectors(), sys.stdout, indent=1)
    else:
        for key, (sig, judge) in SAMPLES.items():
            if sig is None:
                r = from_metrics(PAPER_FIG9_METRICS)
                print(f"{key:16s} C={r['composite']:.3f} formula={r['formula_verdict']:12s} judge={judge:12s} "
                      f"two-key={two_key(judge, r['formula_verdict'])['state']}")
                continue
            a = assay(sig, judge)
            tp = a["tipping_point"]
            print(f"{key:16s} C={a['composite']:.3f} formula={a['formula_verdict']:12s} judge={judge:12s} "
                  f"two-key={a['two_key']['state']:8s} tip={tp['band']}({(tp['min_distance'] or 0):.3f}, {tp['flips'][0]['signal'] if tp['flips'] else '-'}) "
                  f"QFI={a['masking']['qfi']:.2f} mask={a['masking']['masking']} map={a['integrity_map']['quadrant']}")
